#
# Licensed under the EUPL, Version 1.2 or – as soon they will be approved by
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
#
#   https://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.
#
# Run Anshar as proxy or datahandler
#
# Possible values are found in enum AppMode (No modes == All modes)
#
# Examples of valid config-alternatives:
#     - anshar.application.mode=
#     - anshar.application.mode=PROXY
#     - anshar.application.mode=DATA_ET
#     - anshar.application.mode=DATA_ET,DATA_SX,DATA_VM,DATA_SM
#
# baseUrl to where http-requests will be redirected when app runs as proxy.
# anshar.data.handler.baseurl.et=http://anshar-et:8012
# anshar.data.handler.baseurl.vm=http://anshar-vm:8012
# anshar.data.handler.baseurl.sx=http://anshar-sx:8012
activemq.broker.host=localhost
activemq.broker.mgmt.port=18161
# How long should the server be kept alive when not receiving any data
anshar.admin.health.allowed.inactivity.seconds=300
anshar.client.name=ara
anshar.default.max.elements.per.delivery=1000
anshar.default.time.zone=Europe/Paris
anshar.disable.subscription.healthcheck=true
# Should be overridden
anshar.environment=local
# Snapshot-interval - set to negative number to disable
#anshar.export.snapshot.cron.expression= 0 0/10 0/1 ? * * *
anshar.export.snapshot.cron.expression=
anshar.external.et.queue=anshar.external.siri.et.data?asyncConsumer=true&disableReplyTo=true&concurrentConsumers=3
anshar.external.sm.queue=anshar.external.siri.sm.data?asyncConsumer=true&disableReplyTo=true&concurrentConsumers=3
anshar.first.or.last.vj.file=/tmp/ara/chouette/mobiiti_technique/vehicleJourneys/firstOrLastJourney.csv
anshar.gtfs.rt.url.list=
anshar.generate-siri-from-th.enabled=true
anshar.generate-siri-from-th.directory=/tmp/ara/chouette/mobiiti_technique/theoreticalStopMonitoringInfo/
anshar.generate-siri-from-th.file-suffix=_th_sm.csv
anshar.healthcheck.hubot.allowed.inactivity.minutes=15
anshar.healthcheck.hubot.end.time=23:00
anshar.healthcheck.hubot.payload.icon.fail=:heavy_exclamation_mark:
anshar.healthcheck.hubot.payload.icon.success=:heavy_check_mark:
anshar.healthcheck.hubot.payload.message.fail=Not receiving data: {0}
anshar.healthcheck.hubot.payload.message.success=Subscriptions back to normal
anshar.healthcheck.hubot.payload.source=anshar
anshar.healthcheck.hubot.payload.template=\"source\":\"{0}\", \"icon\":\"{1}\", \"message\":\"{2}\"
anshar.healthcheck.hubot.start.time=06:00
anshar.healthcheck.hubot.url=http://hubot/hubot/say
anshar.healthcheck.interval.seconds=30
anshar.inbound.pattern=/{context}/{version}/{type}/{vendor}/{subscriptionId}/{service}/{operation}
anshar.inbound.url=https://64c8-82-66-253-17.ngrok-free.app/anshar
anshar.incoming.concurrentConsumers=5
# Full incoming request is logged to file in this directory when TRACE-logging is enabled
anshar.incoming.logdirectory=target/incoming
anshar.incoming.port=8012
anshar.internal.gtfsrt.stop.monitoring=activemq:queue:gtfsrt.stop.monitoring?asyncConsumer=true&disableReplyTo=true&concurrentConsumers=3
anshar.jmx.metrics.configuration.filepath=
anshar.jmx.metrics.scraping.enabled=true
anshar.kafka.brokers=127.0.0.1:9092
anshar.kafka.clientId=anshar.ara.local
anshar.kafka.enabled=false
anshar.lineIds.file=/tmp/ara/chouette/mobiiti_technique/lines/lines.csv
anshar.login.password=pass
anshar.login.username=user
anshar.mapping.external.ids.root.directory=/tmp/ara/anshar/mappingExternalIdsDir
anshar.mapping.jbvCode.gcs.path=mapping_data/jbv_code_mapping.csv
anshar.mapping.quays.gcs.path=/tmp/ara/tiamat/technique/quayIdMappings.csv
anshar.mapping.stopplaces.gcs.path=/tmp/ara/tiamat/technique/stopPlaceIdMappings.csv
anshar.mapping.parkings.path=/tmp/ara/tiamat/technique/parkingIdMappings.csv
anshar.mapping.stopplaces.update.frequency.min=1
anshar.mapping.stopquayjson.gcs.path=
anshar.mapping.update.frequency.min=60
anshar.message.queue.camel.route.prefix=activemq:queue:
# Tracking period when requestorId is generated
anshar.outbound.adhoc.tracking.period.minutes=2
anshar.outbound.camel.route.topic.et.name=activemq:queue:anshar.estimated_timetables?timeToLive=600000
anshar.outbound.camel.route.topic.sm.name=activemq:queue:anshar.stop_monitoring?timeToLive=600000
anshar.outbound.camel.route.topic.sx.name=activemq:queue:anshar.alerts?timeToLive=600000
anshar.outbound.camel.route.topic.vm.name=activemq:queue:anshar.vehicle_monitoring?timeToLive=600000
anshar.outbound.error.consumeraddress=ConsumerAddress must be set.
anshar.outbound.error.initialtermination=InitialTerminationTime has already passed.
anshar.outbound.error.monitoringref=MonitoringRef must be set.
anshar.outbound.heartbeatinterval.maximum=60000
anshar.outbound.heartbeatinterval.minimum=30000
# Tracking period when explicitly including requestorId
anshar.outbound.polling.tracking.period.minutes=1
anshar.outbound.pubsub.topic.enabled=true
anshar.redis.additionnal.network.vm=
anshar.redis.enabled=false
anshar.route.singleton.policy.automatic.verification=false
anshar.route.singleton.policy.ignore=false
# Kubernetes automatically assigns pod name as HOSTNAME-env variable
anshar.route.singleton.policy.lockValue=
anshar.send.siri.to.kafka=false
anshar.siri.default.producerRef=OKI
# How long to keep the data after it expires
anshar.siri.et.graceperiod.minutes=10
anshar.siri.fm.graceperiod.minutes=10
anshar.siri.sm.graceperiod.minutes=0
anshar.siri.sx.graceperiod.minutes=10
anshar.siri.vm.graceperiod.minutes=10
anshar.stop.times.root.directory=/tmp/ara/chouette/mobiiti_technique/stop_times
# Defines SIRI-datatypes this instance should process.
# Subscriptions of types not listed here will be ignored.
#anshar.subscriptions.datatypes.filter=SITUATION_EXCHANGE, VEHICLE_MONITORING, ESTIMATED_TIMETABLE
anshar.subscriptions.config.path=/home/gcarrere/Idea/MOBI-ITI/Realtime-sandbox/empty.yml
anshar.super.identifier=MOBIITI
anshar.tracking.data.buffer.commit.frequency.seconds=15
anshar.tracking.header.name=ET-Client-Name
anshar.tracking.header.required.get=false
anshar.tracking.header.required.post=false
anshar.trips.root.directory=/tmp/ara/chouette/mobiiti_technique/trips
anshar.validation.data.persist.hours=6
anshar.validation.profile.enabled=true
anshar.validation.profile.name=norway
# Size limit for zipped, validated XML and max number of validations for each subscription
# Validation will be disabled when one of the limits are reached
anshar.validation.total.max.count=20
anshar.validation.total.max.size.mb=4
cron.download.files.mapping=0+0+0+1+1+?+2099
cron.siri=0,30+*+*+?+*+*+*
default.use.original.id=false
external.sx.consumer.enabled=true
external.sx.consumer.queue=activemq:queue:situation.exchange.sic?timeToLive=600000
hazelcast.cluster.name=default
hazelcast.external.service.name=hazelLocal
hazelcast.jmx=true
hazelcast.metrics.enabled=true
hazelcast.port=5702
iam.keycloak.admin.client=fakeClient
iam.keycloak.client.secret=fakeSecret
ishtar.interval.millis=1800000
ishtar.server.url=http://localhost:8881
keycloak.auth-server-url=fakeURL
keycloak.realm=fakeRealm
kishar.server.url=http://localhost:8888
logging.level.no.rutebanken.anshar.routes.siri.Siri20ToSiriWS20Subscription=INFO
logging.level.no.rutebanken.anshar.routes.siri.Siri20ToSiriRS20Subscription=INFO
management.endpoints.prometheus.enabled=true
#management.endpoints.web.exposure.include=info, health, prometheus, env, metrics, loggers
management.endpoints.web.exposure.include=*
management.health.pubsub.enabled=false
management.metrics.enable.jvm=true
management.metrics.enable.logback=false
management.metrics.enable.process=true
management.metrics.enable.system=true
management.metrics.endpoint.export.prometheus.enabled=true
mobi.iti.disruption.api.url=http://0.0.0.0/api-proxy/api/offre/1.0/disruptions/allCurrentDisruptions
outbound.distribution.max.pool.size=200
outbound.distribution.route.connectionsbyroute=500
outbound.distribution.route.maxTotalConnections=1000
outbound.distribution.threads=200
outbound.heartbeat.enabled=false
server.shutdown=graceful
siri.sm.kafka.queue=activemq:queue:siri.stop.monitoring.kafka?timeToLive=600000
spring.activemq.broker-url=tcp://0.0.0.0:61616?jms.redeliveryPolicy.maximumRedeliveries=0
spring.activemq.password=admin
spring.activemq.pooled=true
spring.activemq.user=admin
spring.cloud.gcp.project-id=test
spring.cloud.gcp.pubsub.credentials.location=file:///path/to/google/credentials.json
spring.cloud.gcp.pubsub.project-id=test
spring.data.redis.password=
spring.main.allow-circular-references=true
spring.main.sources=no.rutebanken.anshar
spring.main.web-application-type=none
spring.profiles.active=in-memory-blobstore
# let camel handle quartz startup when camel context is initialized
spring.quartz.auto-startup=false
spring.redis.host=0.0.0.0
spring.redis.port=6379
stop-places.api.url=http://0.0.0.0/api-proxy/api/stop_places/1.0/id/getNetexIdForQuay
urls.lines.mapping.file=https://www.test.fr
urls.stops.mapping.file=https://www.test.fr
anshar.scheduledNotification.enabled=false
interval.check.auto.subscription.restart=300000
download.mapping.files.enabled=false
google.drive.download.required=false
spring.threads.virtual.enabled=true
anshar.initial.delivery.estimated.timetables.queue.name=activemq:queue:initial.delivery.estimated.timetables?disableReplyTo=true
anshar.initial.delivery.stop.monitoring.queue.name=activemq:queue:initial.delivery.stop.monitoring?disableReplyTo=true
anshar.initial.delivery.general.message.queue.name=activemq:queue:initial.delivery.general.message?disableReplyTo=true
anshar.initial.delivery.facility.monitoring.queue.name=activemq:queue:initial.delivery.facility.monitoring?disableReplyTo=true
anshar.initial.delivery.situation.exchange.queue.name=activemq:queue:initial.delivery.situation.exchange?disableReplyTo=true
anshar.initial.delivery.vehicle.monitoring.queue.name=activemq:queue:initial.delivery.vehicle.monitoring?disableReplyTo=true

